### ISSUE TITLE
Error on sencloud extension opencart 2.0.3.1

### ISSUE THREAD

**Issue by vuurvlinder** [SendCloud/SendCloud-OpenCart#9]
WHen I click the button sendcloud i get the following error (ik krijg de volgende error als ik de knop sendcloud druk):

Warning: array_key_exists() expects parameter 2 to be array, null given in /share/CACHEDEV1_DATA/.qpkg/OpenCart/web/admin/controller/sendcloud/sendcloud_api.php on line 254Warning: array_key_exists() expects parameter 2 to be array, null given in /share/CACHEDEV1_DATA/.qpkg/OpenCart/web/admin/controller/sendcloud/sendcloud_api.php on line 260

Enig idee hoe dit op te lossen?

Mvg

Peter

**Comment by Ecno92** [comment]
Hi Peter, 

You have opened a ticket in our support area to solve this problem. We will assist you in solving the issue from there. 

For other people's interest: 
In case of Peter the server seems to return something that is not expected. It can't be handled by the error handler in the client. We've placed some var_dumps to see what is happening in the script. 
This will help us to find the underlying issue. Once we find it we can decide if this needs an adjustment in the client or server side code.

This issue stays open until the issue is resolved.

**Comment by Ecno92** [comment]
The error that occurs is a result of an issue in CURL. It fails to set up a secured connection due to server configuration issues. 
We have placed a if statement in the sendcloud_api.php file to catch any potential errors in the curl request execution so @vuurvlinder can resolve the issue on his server.
```
if(curl_errno($curl_handler))
{
    echo 'error:' . curl_error($curl_handler);
}
```

It seems not to be related to the module itself. So this issue will be closed for now.

**Comment by vuurvlinder** [comment]
Hoi Therry,

 

We hebben een probleem; We hebben 2x de sendcloud button. Ik denk dat er iets dubbel in de root staat. 

Ik heb me helemaal suf gezocht, maar kan het niet vinden. Ik denk ook dat 1 van de gevolgen hiervan is dat bij een bestelling

de klant de bevestiging dubbel krijgt via de mail.

 

Zou jij eens kunnen kijken of jij dit oplossen kan?, met name de dubbele button?

 

 <ftp://dolbee-fashion.nl> ftp://dolbee-fashion.nl

Gn: dolbeefa

Pw: Teddy16

 

http://www.dolbee-fashion.nl/admin/

Gn: admin

Pw: Teddy16!

 

Ps. Verder werkt het prima!

 

Met vriendelijke groeten,

 

Peter Been

Vuurvlinder 20

7943RH Meppel

+31 (0) 522 242801

info@dolbee-fashion.nl

 

 <http://www.dolbee-fashion.nl> www.dolbee-fashion.nl

 

 <http://www.dolbee-fashion.nl/> image004   <https://www.linkedin.com/pub/peter-been/17/94/a0b> image004   <https://www.xing.com/profile/Peter_Been/cv> xing

 

image002

 

Van: Therry van Neerven [mailto:notifications@github.com] 
Verzonden: woensdag 9 september 2015 8:17
Aan: SendCloud/SendCloud-OpenCart
CC: vuurvlinder
Onderwerp: Re: [SendCloud-OpenCart] Error on sencloud extension opencart 2.0.3.1 (#9)

 

The error that occurs is a result of an issue in CURL. It fails to set up a secured connection due to server configuration issues. 
We have placed a if statement in the sendcloud_api.php file to catch any potential errors in the curl request execution so @vuurvlinder <https://github.com/vuurvlinder>  can resolve the issue on his server.

if(curl_errno($curl_handler))
{
    echo 'error:' . curl_error($curl_handler);
}

It seems not to be related to the module itself. So this issue will be closed for now.

**Comment by NiekvanderLinden** [comment]
Hallo vuurvlinder,

Je hebt je ftp gegevens op github gezet en deze zijn openbaar. Om misbruik te voorkomen verander deze gegevens en zou je ons daarna een nieuwe inlog kunnen emailen? (contact@sendcloud.nl)
